### ISSUE TITLE
Errors:  on: memgpt load directory  / embeddings / api: validation error: `inputs` must have less than 512 tokens. LOCAL: sources are not compatible with this agent's embedding model

### ISSUE THREAD

**Issue by quantumalchemy** [cpacker/MemGPT#1086]
**Describe the bug**
TypeError: Got back an unexpected payload from text embedding function, response=
{'message': 'Input validation error: `inputs` must have less than 512 tokens. Given: 646', 'code': 413, 'type': 'Validation'}

**Please describe your setup**
- [x] How did you install memgpt?
pip install pymemgpt -U  - also: pip install pymemgpt-nightly
0.3.4
- [x] Describe your setup
Linux 
Terminal

**MemGPT Config  LOCAL **
```
[defaults]
preset = memgpt_docs
persona = anna_pa
human = basic

[model]
model = ehartford/dolphin-2.5-mixtral-8x7b
model_endpoint = https://api.memgpt.ai 
model_endpoint_type = vllm
model_wrapper = chatml
context_window = 16384

[embedding]
embedding_endpoint_type = local
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /root/.memgpt/chroma

[recall_storage]
type = sqlite
path = /root/.memgpt

[metadata_storage]
type = sqlite
path = /root/.memgpt

[version]
memgpt_version = 0.3.4
```

ERROR:
```
Enter your message: /attach
Warning: the following sources are not compatible with this agent's embedding model and dimension: ['Pseudomonarchia-Daemonum']
Traceback (most recent call last):
  File "/usr/local/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/cli/cli.py", line 689, in run
    run_agent_loop(memgpt_agent, config, first, ms, no_verify)  # TODO: add back no_verify
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/main.py", line 143, in run_agent_loop
    data_source = questionary.select("Select data source", choices=valid_options).ask()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/questionary/prompts/select.py", line 133, in select
    raise ValueError("A list of choices needs to be provided.")
ValueError: A list of choices needs to be provided.

================================================
Using free api endpoint:  https://embeddings.memgpt.ai--->
=================================================
Loading files: 100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/file]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/memgpt/embeddings.py", line 121, in _call_api
    embedding = response_json["data"][0]["embedding"]
                ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/cli/cli_load.py", line 108, in load_directory
    num_passages, num_documents = load_data(
                                  ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/data_sources/connectors.py", line 51, in load_data
    embedding = embed_model.get_text_embedding(passage_text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/embeddings.py", line 131, in get_text_embedding
    return self._call_api(text)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/embeddings.py", line 123, in _call_api
    raise TypeError(f"Got back an unexpected payload from text embedding function, response=\n{response_json}")
TypeError: Got back an unexpected payload from text embedding function, response=
{'message': 'Input validation error: `inputs` must have less than 512 tokens. Given: 597', 'code': 413, 'type': 'Validation'}
```

quickstart free endpoint

**Comment by quantumalchemy** [comment]
hard to believe no one else is experiencing this -- I guess no one is loading  /attaching files or maybe not using chromadb?
- thinking could be env issue I use docker for everything - python 3.11.6  worked on 0.3.3
- maybe incompatible with the llamaindex upgrade on .4
- going to try python 3.12 next 
- What are you guys using? what are you running ver python / what Linux dist?

**Comment by sarahwooders** [comment]
This should be fixed by#1098, but please re-open if not!

**Comment by quantumalchemy** [comment]
payload from text embedding function, response=
{'message': 'Input validation error: `inputs` must have less than 512 tokens. Given: 516', 'code': 413, 'type': 'Validation'}), skipping insert into VectorDB.

-- still getting this embedding error on memgpt_version = 0.3.17
occurs: in cli  > memgpt load directory --name Doc1 --input-files=/root/archive/doc1.pdf
